### ISSUE TITLE
Mount your $HOME folder just to share your code with your container

### ISSUE THREAD

**Issue by cougil** [Marcut-Laurentiu/kata-jenkins#1]
Hi Lau!
Great project and initiative!
I was having a look and I like the idea a lot ;-)
I was playing a bit and the first thing I found is that you won't be able to access your code, because if you are in your container (Jenkins) won't be able to retrieve your project (if you want finally to push it to your own repo your 'Jenkinsfile').
So, may be what you can recommend is mounting your $HOME folder (where you can checkout this project) and pass it as a volume to the container or fork your repo ;-)
Best,
PD: The 'snippet-generator' from the Pipeline plug-in is really cool ;-)

**Comment by Marcut-Laurentiu** [comment]
Hi Nacho!

I'm glad that you like it and thank you for your feedback.
Like you said, there are these two possibilities to use the Jenkinsfile.
I will update the documentation to be more explicit.

Thank you!
